
### EJERCICIO 1 - API RECTÁNGULOS

### 1. Obtener todos los rectángulos
GET http://localhost:3000/rectangulos


### 2. Obtener rectángulo por ID
GET http://localhost:3000/rectangulos/1


### 3. Crear rectángulo
POST http://localhost:3000/rectangulos
Content-Type: application/json

{
    "base": 10,
    "altura": 5
}


### 4. Crear otro rectángulo
POST http://localhost:3000/rectangulos
Content-Type: application/json

{
    "base": 8,
    "altura": 4
}


### 5. Validación - base negativa
POST http://localhost:3000/rectangulos
Content-Type: application/json

{
    "base": -8,
    "altura": 4
}


### 6. Validación - altura igual a 0
POST http://localhost:3000/rectangulos
Content-Type: application/json

{
    "base": 8,
    "altura": 0
}


### 7. Validación - base no numérica
POST http://localhost:3000/rectangulos
Content-Type: application/json

{
    "base": "abc",
    "altura": 4
}


### 8. Validación - no permitir perímetro enviado por el cliente
POST http://localhost:3000/rectangulos
Content-Type: application/json

{
    "base": 10,
    "altura": 5,
    "perimetro": 100
}


### 9. Validación - no permitir superficie enviada por el cliente
POST http://localhost:3000/rectangulos
Content-Type: application/json

{
    "base": 10,
    "altura": 5,
    "superficie": 100
}


### 10. Modificar rectángulo
PUT http://localhost:3000/rectangulos/1
Content-Type: application/json

{
    "base": 12,
    "altura": 6
}


### 11. Modificar con valores inválidos
PUT http://localhost:3000/rectangulos/1
Content-Type: application/json

{
    "base": -5,
    "altura": 6
}


### 12. Obtener ID inexistente
GET http://localhost:3000/rectangulos/999


### 13. Modificar ID inexistente
PUT http://localhost:3000/rectangulos/999
Content-Type: application/json

{
    "base": 10,
    "altura": 5
}


### 14. Eliminar rectángulo
DELETE http://localhost:3000/rectangulos/1


### 15. Eliminar ID inexistente
DELETE http://localhost:3000/rectangulos/999


### 16. Obtener todos nuevamente
GET http://localhost:3000/rectangulos